- name: Getting information about current BIOS version
  uri:
    url: https://{{ ansible_host }}{{ basicPathToApi }}{{ pathForVersion }}
    validate_certs: "{{ iloValidateCerts }}"
    method: "{{ apiMethodGet }}"
    force_basic_auth: "{{ iloForceBasicAuth }}"
    user: "{{ iloUser }}"
    password: "{{ iloPassword }}"
    body_format: "{{ iloBodyFormat }}"
  delegate_to: "{{ delegateToLocalhost }}"
  register: versionBios

- name: debug versionBios
    debug: 
      var: versionBios.json.BiosVersion
    register: versionIloBeforeUpdate